
service: nfl-api
# app: nfl
org: gavswe

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  timeout: 15

functions:
  downAndDistance:
    handler: downAndDistance.downAndDistance
    events:
      - httpApi:
          path: /downAndDistance
          method: post
  
  passingBoard:
    handler: leaderboards/passingBoard.passingBoard
    events:
      - httpApi:
          path: /passingBoard
          method: post

  rushingBoard:
    handler: leaderboards/rushingBoard.rushingBoard
    events:
      - httpApi:
          path: /rushingBoard
          method: post

  receivingBoard:
    handler: leaderboards/receivingBoard.receivingBoard
    events:
      - httpApi:
          path: /receivingBoard
          method: post
    
plugins:
  - serverless-python-requirements
